### ISSUE TITLE
Textured Cube

### ISSUE THREAD

**Issue by kanerogers** [kanerogers/gambier#3]
## TODO
  - [x] Load `base_colour` image from `gltf`
  - [x] Upload image to GPU
  - [x] Transition image
  - [x] De-duplicate materials / meshes
  - [x] Create sampler
